## Logistic Regression Implementation

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.datasets import make_classification

import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = load_iris()

In [3]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [4]:
df = pd.DataFrame(dataset.data, columns = dataset.feature_names)

In [5]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
df['target'] = dataset.target

In [7]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [8]:
df['target'].unique()

array([0, 1, 2])

In [9]:
df[df['target'] != 2]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 5.1               3.5                1.4               0.2   
1                 4.9               3.0                1.4               0.2   
2                 4.7               3.2                1.3               0.2   
3                 4.6               3.1                1.5               0.2   
4                 5.0               3.6                1.4               0.2   
..                ...               ...                ...               ...   
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
95       1  
96       1  
97       1  
98       1  
99       1  

[100 rows x 5 columns]

In [10]:
df_copy = df[df['target'] != 2]

In [11]:
df_copy['target'].unique()

array([0, 1])

In [12]:
# Independent and dependent features

X = df_copy.iloc[:, :-1]
y = df_copy.iloc[:, -1]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [14]:
classification = LogisticRegression(max_iter = 200)

In [15]:
classification

LogisticRegression(max_iter=200)

In [16]:
classification.fit(X_train, y_train)

LogisticRegression(max_iter=200)

In [17]:
y_pred = classification.predict(X_test)

In [18]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion Metrics,Accuracy,Classification Report

In [19]:
print(confusion_matrix(y_test, y_pred))

[[12  0]
 [ 0  8]]


In [20]:
print(accuracy_score(y_test, y_pred))

1.0


In [21]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Cross Validation

In [22]:
cv = KFold(n_splits = 5)

In [23]:
cv

KFold(n_splits=5, random_state=None, shuffle=False)

In [24]:
# these are the scores all the cross validation
scores = cross_val_score(classification, X_train, y_train, scoring = 'accuracy', cv = cv)

In [25]:
np.mean(scores)

1.0

In [26]:
# Lets see more complex data

X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=2, random_state=1)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [28]:
complex_class_model=LogisticRegression(max_iter=200)

In [29]:
complex_class_model.fit(X_train,y_train)

LogisticRegression(max_iter=200)

In [30]:
y_pred_complex=complex_class_model.predict(X_test)

In [31]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



In [32]:
# Cross Validation
cv = KFold(n_splits = 5)
cross_val_score(complex_class_model, X_train, y_train, cv=cv)

array([0.80625, 0.78125, 0.79375, 0.8125 , 0.85625])

# Logisitic Regression Hyperparameter Tuning

## GridsearchCV

In [33]:
# Define the parameter grid
param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.1, 1.0, 10],
    'solver': ['liblinear', 'saga']  # Solvers that support 'l1' penalty
}

In [34]:
# Initialize LogisticRegression
logreg = LogisticRegression()

In [35]:
# Perform Grid Search
clf = GridSearchCV(logreg, param_grid, cv=5)
clf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1.0, 10], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear', 'saga']})

In [36]:
# Get the best parameters from GridSearchCV
print("Best Parameters: ", clf.best_params_)

Best Parameters:  {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}


In [37]:
# Get the best score from GridSearchCV
print("Best Score: ", clf.best_score_)

Best Score:  0.81125


In [38]:
classifier = LogisticRegression(C=1, penalty='l2')

In [39]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [40]:
y_pred=classifier.predict(X_test)

In [41]:
y_pred

array([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1])

In [42]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[78 13]
 [29 80]]
0.79
              precision    recall  f1-score   support

           0       0.73      0.86      0.79        91
           1       0.86      0.73      0.79       109

    accuracy                           0.79       200
   macro avg       0.79      0.80      0.79       200
weighted avg       0.80      0.79      0.79       200



## Randomized Search cv

In [43]:
# Update parameter grid to match compatible solvers and penalties
param_distributions = {
    'C': [1, 10, 20, 30],
    'penalty': ['l1', 'l2'],  # Elasticnet is only supported by saga
    'solver': ['liblinear', 'saga']  # Solvers that support 'l1' penalty
}

In [44]:
# Perform RandomizedSearchCV
random_clf = RandomizedSearchCV(LogisticRegression(), param_distributions=param_distributions, cv=5, n_iter=20)
random_clf.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ['l1', 'l2'],
                                        'solver': ['liblinear', 'saga']})

In [45]:
# Get the best parameters
print("Best Parameters: ", random_clf.best_params_)

Best Parameters:  {'solver': 'liblinear', 'penalty': 'l1', 'C': 1}


In [46]:
# Get the best score from RandomizedSearchCV
print("Best Score: ", random_clf.best_score_)

Best Score:  0.8087500000000001


# Logistic Regression For Multiclass Classification

In [47]:
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [48]:
# define the multinomial logistic regression model For multiclass classification
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [50]:
# trianing model
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [51]:
y_pred=model.predict(X_test)

In [52]:
y_pred

array([1, 1, 0, 2, 1, 2, 2, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0,
       2, 1, 0, 1, 1, 0, 2, 2, 0, 1, 0, 1, 0, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 2, 0, 1,
       2, 1, 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2,
       1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1,
       0, 1, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       2, 2, 2, 2, 2, 2, 0, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 0,
       2, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2, 1, 0,
       2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0])

In [53]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[56 10 17]
 [16 41  6]
 [ 3 13 38]]
0.675
              precision    recall  f1-score   support

           0       0.75      0.67      0.71        83
           1       0.64      0.65      0.65        63
           2       0.62      0.70      0.66        54

    accuracy                           0.68       200
   macro avg       0.67      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200

