# Assignment (26th Feb) : Numpy

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

**ANS:** Yes, there is a difference in the data types of list_ and array_list after the conversion.

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(list_)

print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

Data type of list_: <class 'str'>
Data type of array_list: <U1


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(list_)

print("Data types in list_:")
for element in list_:
    print(type(element))
    
print("\nData types in array_list:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

**ANS**: Yes, there will be a difference in the data type of the elements in list_ and array_list when you specify dtype=int during the conversion. The array_list will now contain integers instead of strings.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object = list_, dtype = int)

print("Data types in list_:")
for element in list_:
    print(type(element))

print("\nData types in array_list:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape

(ii) size

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]

num_array = np.array(num_list)

print("Shape of num_array:", num_array.shape)

print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [5]:
import numpy as np

zero_matrix = np.zeros((3, 3))

print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [6]:
import numpy as np

identity_matrix = np.identity(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
